# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.14

ci:
  # Renovate updates the file. We can't disable pre-commit CI's autoupdate entirely
  # but this is the least frequent we can make it.
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.32.1
    hooks:
      - id: basedpyright

  - repo: https://github.com/ewjoachim/sync-pre-commit-with-uv
    rev: 1.1.0
    hooks:
      - id: sync
